### ISSUE TITLE
snakefile ignores participants.tsv

### ISSUE THREAD

**Issue by jclauneuro** [akhanf/zona-diffparc#4]
The Snakefile currently ignores the `participants_tsv` file and uses the list of subjects in `seed_seg_dir` instead.

Should enforce list of participants either with local list of participants in the same directory as the Snakefile or elsewhere.

**Comment by akhanf** [comment]
Left out using the participants.tsv in bids for since it had extra subjects making snakemake complain about missing files. We can have the user specify a participants tsv directly , or alternatively a simple text file with IDs? I think the participants tsv (read with pandas) is better since gives more flexibility to add other info..

**Comment by jclauneuro** [comment]
Yeah it took some digging to sort out how participants were being included into the snakemake execution. I think a local `participants.tsv` to be placed in either the root directory for the snakemake pipeline or `cfg` or some other subfolder would make sense. Yes, could also include other demographic data there too.

**Comment by akhanf** [comment]
@jclauneuro let me know what you think about the linked pull-request.. Having a tsv file in the working folder is actually what snakemake recommends in their gold-standard workflows: https://github.com/snakemake-workflows/docs

**Comment by jclauneuro** [comment]
Pull request approved. Good to hear this is consistent with recommendations for gold-standard snakemake workflows.
